# Generated by Django 3.2.6 on 2021-12-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='movie_id',
        ),
    ]
