# Generated by Django 3.2.6 on 2021-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_review_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('movie_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
