# Generated by Django 3.2.6 on 2021-12-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_movie_front_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
