# Generated by Django 3.2.6 on 2022-01-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_title', models.CharField(max_length=100, unique=True)),
                ('jd', models.CharField(max_length=1000)),
                ('dept_name', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
